import {supabaseConfig as config} from './supabase-config.js';
import {esc,field} from './ui.js';
const root=document.querySelector('#join'),message=document.querySelector('#message');
let fragment=new URLSearchParams(location.hash.slice(1)),invite=fragment.get('invite'),session='',details=null,busy=false;
const confirmed=!!fragment.get('access_token');history.replaceState(null,'',location.pathname);fragment=null;
async function request(path,body,token=''){const r=await fetch(config.url+path,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});let result;try{result=await r.json();}catch{throw Error('서버 응답을 확인하지 못했습니다.');}if(!r.ok){if(result.code==='email_address_not_authorized'||result.code==='over_email_send_rate_limit')throw Error('운영자가 자동 이메일 인증 설정을 끈 뒤 다시 시도해 주세요.');if(result.code==='email_not_confirmed')throw Error('이전 이메일 인증 방식에서 대기 중인 계정입니다. 운영자에게 계정 상태 확인을 요청해 주세요.');if(result.code==='invalid_credentials')throw Error('이메일 또는 비밀번호를 확인해 주세요.');if(result.code==='user_already_exists')throw Error('이미 가입한 이메일입니다. 로그인 버튼을 사용해 주세요.');if(result.code==='weak_password')throw Error('더 긴 비밀번호에 영문·숫자·기호를 함께 사용해 주세요.');throw Error(result.message||result.msg||'요청을 처리하지 못했습니다.');}return result;}
function auth(){root.innerHTML=`<section class="card"><p class="eyebrow">관리자 초대</p><h1>${esc(details.workspace_name)}</h1><p>${esc(details.email)} 담당자님을 초대했습니다.</p><form id="auth">${field('email','초대받은 이메일','email',`value="${esc(details.email)}" readonly autocomplete="username"`)}${field('password','비밀번호','password','minlength="8" maxlength="128" autocomplete="current-password"')}<label class="field">처음 가입하는 경우 비밀번호 다시 입력<input type="password" name="confirm" autocomplete="new-password" maxlength="128"></label><div class="toolbar"><button class="btn" name="mode" value="login">로그인</button><button class="btn secondary" name="mode" value="signup">처음 가입하기</button></div></form><p>이메일은 로그인 아이디로 사용합니다. 자동 인증메일이나 별도 승인 없이 초대 링크로 관리자 등록을 완료합니다.</p></section>`;}
function setup(){root.innerHTML=`<section class="card"><h1>${esc(details.workspace_name)} 시작하기</h1><p>${details.transfer?'기존 Workspace를 인수합니다. 기존 단원·일정·출결은 유지됩니다.':'정보를 입력하면 Workspace와 첫 찬양대가 만들어집니다.'}</p><form id="accept">${field('name','관리자 이름','text','maxlength="80"')}${field('login','한글 아이디','text','maxlength="64" placeholder="띄어쓰기 없이 입력"')}${details.transfer?'':field('choir','첫 찬양대 이름','text','maxlength="80"')}<button class="btn">${details.transfer?'관리자 인수 완료':'관리자 등록 완료'}</button></form></section>`;}
async function run(fn){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);message.textContent='처리 중입니다…';try{await fn();}catch(e){message.textContent=e.name==='TimeoutError'?'응답이 늦어지고 있습니다. 같은 화면에서 다시 시도해 주세요.':e.message;}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
root.addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target)),mode=e.submitter?.value;run(async()=>{if(e.target.id==='auth'){if(mode==='signup'){if(values.password!==values.confirm)throw Error('두 비밀번호가 일치하지 않습니다.');const redirect=new URL('./join.html',location.href).href;const result=await request('/auth/v1/signup?redirect_to='+encodeURIComponent(redirect),{email:details.email,password:values.password});e.target.reset();if(result.access_token){session=result.access_token;setup();message.textContent='가입 상태를 확인했습니다. 아래 정보를 입력해 주세요.';}else message.textContent='아직 이메일 인증 설정이 켜져 있습니다. 운영자에게 자동 인증메일 설정을 꺼 달라고 요청해 주세요.';}else{const result=await request('/auth/v1/token?grant_type=password',{email:details.email,password:values.password});session=result.access_token;e.target.reset();setup();message.textContent='로그인했습니다.';}}else if(e.target.id==='accept'){const result=await request('/rest/v1/rpc/choiron_accept_invite',{p_token:invite,p_admin_name:values.name,p_login_id:values.login,p_choir_name:values.choir||''},session);invite='';session='';root.innerHTML=`<section class="card"><h1>${esc(result.name)} 준비 완료</h1><p>관리자 화면에서 이메일·비밀번호로 로그인하세요.</p><a class="btn" href="./operator.html">관리자 화면 열기</a></section>`;message.textContent='관리자 등록을 완료했습니다.';}});});
root.innerHTML='<section class="card"><h1>관리자 초대 확인</h1><a href="./operator.html">이미 가입했다면 관리자 로그인</a></section>';
if(invite&&/^[a-f0-9]{64}$/.test(invite))run(async()=>{details=await request('/rest/v1/rpc/choiron_invite_preview',{p_token:invite});if(details.access_mode!=='direct_link')throw Error('운영자가 관리자 초대 설정(008)을 적용한 뒤 사용할 수 있습니다.');auth();message.textContent='';});else{root.innerHTML='<section class="card"><h1>관리자 초대</h1><p>운영자가 보내 준 원래 초대 링크로 접속해 주세요.</p><a class="btn secondary" href="./operator.html">이미 가입했다면 관리자 로그인</a></section>';message.textContent=confirmed?'이메일 인증 후에는 원래 초대 링크를 다시 열어 가입을 마무리해 주세요.':'';}
