import {partField,bindParts} from './part-field.js?v=1';
import {invitePanel} from './member-invites.js?v=2';
import {esc,field,date,position} from './ui.js';
export async function manage({root,rpc,workspace,back}){
 bindParts(root);
 let choir=workspace.choirs[0]?.id,data,working=false;
 if(!choir)throw Error('등록된 찬양대가 없습니다.');
 root.innerHTML=`<section class="card"><button class="btn secondary" id="admin-back">← 내 Workspace</button><h2>${esc(workspace.name)} 관리</h2><label class="field">찬양대<select id="choir">${workspace.choirs.map(c=>`<option value="${esc(c.id)}">${esc(workspace.name+' · '+c.name)}</option>`).join('')}</select></label><p>단원 접속 링크</p><input id="member-link" readonly aria-label="단원 접속 링크"><button class="btn secondary" id="copy-link">링크 복사</button><p class="muted" id="local-note"></p><div class="toolbar"><button class="btn secondary" data-tab="members">단원</button><button class="btn secondary" data-tab="places">장소</button><button class="btn secondary" data-tab="sessions">일정·출결</button></div></section><p id="admin-message" role="status"></p><div id="admin-content"></div>`;
 const notice=root.querySelector('#admin-message'),content=root.querySelector('#admin-content');
 const link=new URL('./member.html',location.href);link.searchParams.set('workspace',workspace.id);root.querySelector('#member-link').value=link.href;
 root.querySelector('#local-note').textContent=location.hostname==='127.0.0.1'||location.hostname==='localhost'?'현재는 이 PC에서 시험하는 주소입니다. GitHub Pages에 배포한 후 단원에게 공유하세요.':'이미 가입한 단원의 로그인 링크입니다. 처음 가입할 단원에게는 아래 가입 링크를 보내 주세요.';
 async function load(){data=await rpc('choiron_admin_data',{p_workspace:workspace.id,p_choir:choir});}
 const table=(headers,rows)=>`<div style="overflow:auto"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
 function render(tab){
  if(tab==='members'){content.innerHTML=`<section class="card" id="enrollment"></section><section class="card"><h2>단원 등록</h2><form data-action="member">${field('name','이름','text','maxlength="80"')}${field('login_id','로그인 아이디 · 한글 가능','text','maxlength="64"')}${partField()}${field('pin','초기 PIN · 숫자 6~12자리','password','inputmode="numeric" pattern="[0-9]{6,12}" minlength="6" maxlength="12" autocomplete="new-password"')}<p class="muted">처음 로그인할 때 PIN을 바꾸거나 그대로 사용할 수 있습니다. 같은 Workspace의 기존 아이디를 입력하면 해당 단원을 이 찬양대에 추가하며 기존 PIN은 유지됩니다.</p><button class="btn">단원 등록</button></form></section><section class="card"><h2>단원 ${data.members.length}명</h2>${table(['이름','아이디','파트','계정 관리'],data.members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.login_id)}</td><td>${esc(m.part)}</td><td><details><summary>PIN 초기화·역할</summary>${m.login_id===workspace.login_id?'<p>이메일로 로그인하는 Workspace 관리자입니다. PIN 대신 이메일 비밀번호 재설정을 이용해 주세요.</p>':`<form data-action="reset_pin"><input type="hidden" name="member_id" value="${m.id}">${field('pin','새 임시 PIN · 숫자 6~12자리','password','inputmode="numeric" pattern="[0-9]{6,12}" maxlength="12" autocomplete="new-password"')}<p class="muted">저장하면 이 단원의 기존 로그인이 해제됩니다. 기존 PIN은 조회할 수 없습니다.</p><button class="btn secondary">PIN 초기화</button></form>`}<form data-action="roles"><input type="hidden" name="member_id" value="${m.id}">${[['member','단원'],['leader','파트장'],['secretary','서기'],['admin','관리자']].map(([r,label])=>`<label><input type="checkbox" name="roles" value="${r}" ${m.roles?.includes(r)?'checked':''}>${label}</label>`).join(' ')}<button class="btn secondary">역할 저장</button></form></details></td></tr>`))}</section>`;
  if(tab==='members')invitePanel({host:content.querySelector('#enrollment'),rpc,workspace:workspace.id,choir,label:workspace.name+' · '+workspace.choirs.find(c=>c.id===choir).name});}
  if(tab==='places')content.innerHTML=`<section class="card"><h2>출석 장소 등록</h2><p>연습 장소에 계시면 ‘현재 위치 사용’을 누르세요.</p><form data-action="place" data-request="${crypto.randomUUID()}">${field('name','장소 이름','text','maxlength="100"')}<button class="btn secondary" type="button" id="locate">현재 위치 사용</button>${field('latitude','위도','number','min="-90" max="90" step="any"')}${field('longitude','경도','number','min="-180" max="180" step="any"')}${field('radius_m','출석 허용 반경 (미터)','number','min="10" max="3000" value="150"')}<button class="btn">장소 저장</button></form></section><section class="card">${data.places.map(p=>`<p>${esc(p.name)} · 반경 ${p.radius_m}m</p>`).join('')||'아직 등록한 장소가 없습니다.'}</section>`;
  if(tab==='sessions')content.innerHTML=`<section class="card"><h2>연습 일정 등록</h2>${data.places.length?`<form data-action="session" data-request="${crypto.randomUUID()}">${field('title','일정 이름','text','maxlength="100"')}<label class="field">장소<select name="place_id">${data.places.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><p class="muted">모든 시간은 한국 시간입니다. 출석은 연습 종료 시간에 마감됩니다.</p>${field('starts_at','연습 시작','datetime-local')}${field('ends_at','연습 종료','datetime-local')}${field('hours_before','출석 허용 · 연습 시작 몇 시간 전','number','min="0" max="168" step="0.5" value="1"')}<p class="muted">기본 1시간 전 · 0.5는 30분 전입니다.</p><button class="btn">일정 저장</button></form>`:'먼저 장소 탭에서 출석 장소를 등록해 주세요.'}</section><section class="card"><h2>일정·출결</h2>${data.sessions.map(s=>`<details><summary>${esc(s.title)} · ${date(s.starts_at)}</summary><p>출석: ${data.attendance.filter(a=>a.session_id===s.id&&a.status==='present').length}명</p><form data-action="correct"><input name="session_id" type="hidden" value="${s.id}"><label class="field">단원<select name="member_id">${data.members.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><label class="field">출결<select name="status"><option value="present">출석</option><option value="absent">결석</option><option value="excused">공결</option></select></label>${field('reason','정정 사유','text','maxlength="500"')}<button class="btn secondary">출결 정정 저장</button></form></details>`).join('')||'아직 등록한 일정이 없습니다.'}</section>`;
 }
 async function run(fn){if(working)return;working=true;root.querySelectorAll('button,select').forEach(b=>b.disabled=true);notice.textContent='처리 중입니다…';try{await fn();}catch(e){notice.textContent=e.message;}finally{working=false;root.querySelectorAll('button,select').forEach(b=>b.disabled=false);}}
 root.onclick=e=>{if(working)return;if(e.target.id==='admin-back'){back();return;}if(e.target.dataset.tab){render(e.target.dataset.tab);notice.textContent='';}if(e.target.id==='copy-link')run(async()=>{await navigator.clipboard.writeText(link.href);notice.textContent='링크를 복사했습니다.';});if(e.target.id==='locate')run(async()=>{const p=await position();for(const k of ['latitude','longitude'])content.querySelector(`[name=${k}]`).value=p[k];notice.textContent='현재 위치를 입력했습니다. 장소 저장을 눌러 주세요.';});};
 root.onchange=e=>{if(e.target.id==='choir')run(async()=>{choir=e.target.value;await load();render('members');notice.textContent='';});};
 root.onsubmit=e=>{if(!e.target.dataset.action)return;e.preventDefault();e.stopImmediatePropagation();const form=e.target,action=form.dataset.action,values=Object.fromEntries(new FormData(form));if(action==='roles')values.roles=new FormData(form).getAll('roles');run(async()=>{if(form.dataset.request)values.id=form.dataset.request;if(action==='session'){const hours=Number(values.hours_before),start=new Date(values.starts_at+':00+09:00'),end=new Date(values.ends_at+':00+09:00');if(!Number.isFinite(hours)||hours<0||hours>168||hours*2%1!==0)throw Error('출석 허용 시간을 0~168시간 사이, 0.5시간 단위로 입력해 주세요.');if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)throw Error('연습 종료는 시작 시간보다 뒤로 설정해 주세요.');values.starts_at=start.toISOString();values.ends_at=end.toISOString();values.opens_at=new Date(start.getTime()-hours*3600000).toISOString();values.closes_at=values.ends_at;delete values.hours_before;}if(['reset_pin','roles'].includes(action)){await rpc('choiron_admin_member_settings',{p_workspace:workspace.id,p_choir:choir,p_member:values.member_id,p_action:action,p_data:values});}else await rpc('choiron_admin_save',{p_workspace:workspace.id,p_choir:choir,p_action:action,p_data:values});if(form.elements.pin)form.elements.pin.value='';delete values.pin;try{await load();render(['member','reset_pin','roles'].includes(action)?'members':action==='place'?'places':'sessions');notice.textContent='저장했습니다.';}catch{notice.textContent='저장됐지만 목록을 갱신하지 못했습니다. 돌아갔다가 다시 열어 주세요.';}});};
 try{await load();render('members');}catch(e){notice.textContent=e.message;}
}
