export const kday=value=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date(value));
export const stamp=value=>new Date(value).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
const clean=s=>String(s??'').replace(/\\/g,'\\\\').replace(/\r?\n|\r/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function fold(s){let out='',n=0;for(const ch of s){const size=new TextEncoder().encode(ch).length;if(n+size>75){out+='\r\n ';n=1;}out+=ch;n+=size;}return out;}
const eventTitle=s=>s.workspace_name?s.workspace_name+' · '+s.choir_name+' — '+s.title:s.title;
export function ics(session,workspace){return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ChoirON//KO','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${workspace}-${session.choir_id}-${session.id}@choiron`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(session.starts_at)}`,`DTEND:${stamp(session.ends_at)}`,`SUMMARY:${clean(eventTitle(session))}`,`DESCRIPTION:${clean(session.choir_name)}`,`LOCATION:${clean(session.place)}`,`STATUS:${session.status==='cancelled'?'CANCELLED':'CONFIRMED'}`,'END:VEVENT','END:VCALENDAR'].map(fold).join('\r\n')+'\r\n';}
export function googleCalendar(s){const url=new URL('https://calendar.google.com/calendar/render');url.search=new URLSearchParams({action:'TEMPLATE',text:eventTitle(s),dates:stamp(s.starts_at)+'/'+stamp(s.ends_at),details:s.choir_name,location:s.place,ctz:'Asia/Seoul'});return url.href;}
export function report(rows,year,month='',search=''){const q=search.trim().toLocaleLowerCase();const filtered=rows.filter(s=>kday(s.starts_at).startsWith(String(year)+(month?'-'+month:''))&&(!q||[s.title,s.choir_name,s.place,s.reason].some(x=>String(x??'').toLocaleLowerCase().includes(q))));return {rows:filtered,counts:{present:filtered.filter(s=>s.status!=='cancelled'&&s.attendance==='present').length,absent:filtered.filter(s=>s.status!=='cancelled'&&s.attendance==='absent').length,excused:filtered.filter(s=>s.status!=='cancelled'&&s.attendance==='excused').length,unrecorded:filtered.filter(s=>s.status!=='cancelled'&&!s.attendance&&new Date(s.closes_at)<new Date()).length}};}
export async function photoData(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10000000)throw Error('10MB 이하의 JPG·PNG·WebP 사진을 선택해 주세요.');const image=await createImageBitmap(file);try{const canvas=document.createElement('canvas');const scale=Math.min(1,320/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',0.78);if(data.length>140000)throw Error('더 작은 사진을 선택해 주세요.');return data;}finally{image.close();}}
