import {setAppIcon} from './pwa.js?v=1';
import {invitePanel} from './member-invites.js?v=2';
import {applyTheme} from './themes.js?v=2';
import {supabaseConfig as config} from './supabase-config.js';
import {esc,field,date,position} from './ui.js';
import {kday,ics,googleCalendar,report,photoData} from './member-utils.js';
const root=document.querySelector('#screen'),message=document.querySelector('#message');
const valid=id=>/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(id||'');
const today=()=>kday(new Date()),currentYear=()=>Number(today().slice(0,4));
let workspace=new URL(location.href).searchParams.get('workspace'),token='',busy=false,data=null,view='home',year=currentYear(),month=today().slice(0,7),selectedDay=today(),reportMonth='',query='',staff=null,staffChoir='';
const sessions=new Map(), snapshots=new Map(), connectionErrors=new Map();let choirFilter='';let remembered=[];
const scopedAction=(id,name,values={})=>rpc('choiron_member_action',{p_token:sessions.get(id),p_action:name,p_data:values});
function allRows(){return [...snapshots.entries()].filter(([id,d])=>sessions.has(id)&&!connectionErrors.has(id)&&d.year===year).flatMap(([id,d])=>d.sessions.map(s=>({...s,workspace_id:id,workspace_name:d.workspace}))).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));}
const shownRows=()=>allRows().filter(s=>!choirFilter||s.workspace_id+'/'+s.choir_id===choirFilter);
async function refreshAll(y=year,exclude=null){await Promise.allSettled([...sessions.keys()].filter(id=>id!==exclude).map(async id=>{try{const next=await scopedAction(id,'data',{year:y});next.year=y;snapshots.set(id,next);connectionErrors.delete(id);if(id===workspace)data=next;}catch(e){connectionErrors.set(id,e.message);}}));year=y;}
async function refreshOne(id){try{const next=await scopedAction(id,'data',{year});next.year=year;snapshots.set(id,next);connectionErrors.delete(id);if(id===workspace)data=next;}catch(e){connectionErrors.set(id,e.message);throw e;}}
function overviewControls(){const options=[...snapshots.entries()].filter(([id])=>sessions.has(id)).flatMap(([id,d])=>(d.memberships||[]).map(m=>({key:id+'/'+m.choir_id,label:d.workspace+' · '+m.name})));if(choirFilter&&!options.some(o=>o.key===choirFilter))choirFilter='';return `<section class="card"><label class="field">볼 합창단<select id="choir-filter"><option value="">전체 합창단</option>${options.map(o=>`<option value="${esc(o.key)}" ${choirFilter===o.key?'selected':''}>${esc(o.label)}</option>`).join('')}</select></label><button class="btn secondary" id="refresh-all">일정 새로고침</button><p class="member-label">로그인한 곳의 일정을 함께 표시합니다. 내 정보·출결 관리는 선택한 계정 기준입니다.</p>${[...connectionErrors].map(([id,error])=>`<p role="alert">${esc(remembered.find(w=>w.id===id)?.name||'합창단')}: 일정을 불러오지 못했습니다. ${esc(error)} <button class="btn secondary" data-retry="${id}">다시 시도</button><button class="btn secondary" data-relogin="${id}">다시 로그인</button></p>`).join('')}</section>`;}

try{remembered=JSON.parse(localStorage.getItem('choiron-member-workspaces')||'[]');if(!Array.isArray(remembered))remembered=[];remembered=remembered.filter(w=>valid(w.id)&&typeof w.name==='string').slice(0,30);}catch{remembered=[];}
function remember(){remembered=[{id:workspace,name:data.workspace},...remembered.filter(w=>w.id!==workspace)].slice(0,30);try{localStorage.setItem('choiron-member-workspaces',JSON.stringify(remembered));}catch{}sessions.set(workspace,token);const url=new URL(location.href);url.searchParams.set('workspace',workspace);window.history.replaceState(null,'',url);}
async function rpc(name,args){const r=await fetch(config.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(20000)});let result;try{result=await r.json();}catch{throw Error('서버 응답을 확인하지 못했습니다.');}if(!r.ok||result.error){if(result.code==='PGRST202')throw Error('관리자가 추가 설정 SQL을 적용해야 합니다.');throw Error(result.error||result.message||'요청을 처리하지 못했습니다.');}return result;}
const action=(name,values={})=>rpc('choiron_member_action',{p_token:token,p_action:name,p_data:values});
async function load(y=year){const next=await action('data',{year:y});data=next;data.year=y;year=y;snapshots.set(workspace,data);connectionErrors.delete(workspace);applyTheme(data.theme,data.logo);setAppIcon(data.logo).catch(()=>{});remember();await refreshAll(y,workspace);}
function login(){applyTheme();root.innerHTML=`<section class="card"><p class="eyebrow">함께하는 찬양</p><h1>${esc(remembered.find(w=>w.id===workspace)?.name||'단원 로그인')}</h1><p>받으신 아이디와 PIN을 입력해 주세요.</p><form id="login">${field('loginId','아이디 · 한글 가능','text','maxlength="64" autocomplete="username"')}${field('pin','PIN · 숫자 6~12자리','password','inputmode="numeric" pattern="[0-9]{6,12}" maxlength="12" autocomplete="current-password"')}<button class="btn">로그인</button></form><p>처음 오셨나요?</p><a class="btn secondary" href="./member-join.html">회원가입 · 가입 링크 입력</a></section>`;}
function pin(first=false){root.innerHTML=`<section class="card"><h1>${first?'내 PIN 정하기':'PIN 변경'}</h1><p>숫자 6~12자리로 정해 주세요.</p><form id="pin">${field('pin','새 PIN','password','inputmode="numeric" pattern="[0-9]{6,12}" maxlength="12" autocomplete="new-password"')}${field('confirm','새 PIN 다시 입력','password','inputmode="numeric" maxlength="12" autocomplete="new-password"')}<button class="btn">저장하고 시작하기</button></form><div class="toolbar">${first?'<button class="btn secondary" id="skip-pin">지금은 변경하지 않기</button>':'<button class="btn secondary" data-view="profile">돌아가기</button>'}<button class="btn secondary" id="logout">로그아웃</button></div></section>`;}
const staffMemberships=()=> (data?.memberships||[]).filter(m=>m.roles.some(r=>['leader','secretary','admin'].includes(r)));
function nav(){return `<nav class="member-nav" aria-label="단원 메뉴">${[['home','홈'],['calendar','일정'],['history','내 출결'],['profile','내 정보'],...(staffMemberships().length?[['staff','출결 관리']]:[])].map(([id,label])=>`<button data-view="${id}" ${view===id?'aria-current="page"':''}>${label}</button>`).join('')}</nav>`;}
const empty=text=>`<section class="card empty">${text}</section>`;
function status(s){return s.status==='cancelled'?'취소된 일정':({present:'출석 완료',absent:'결석',excused:'공결'}[s.attendance]||(s.reason?'결석 예정: '+s.reason:'출석 기록 없음'));}
function cards(rows,canCheck=true){return rows.map(s=>{const now=new Date(),open=new Date(s.opens_at)<=now&&now<=new Date(s.closes_at),active=s.status!=='cancelled',key=esc(s.workspace_id+'/'+s.choir_id+'/'+s.id);return `<section class="card"><p class="eyebrow">${esc(s.workspace_name+' · '+s.choir_name)}</p><h2>${esc(s.title)}</h2><p>${date(s.starts_at)} ~ ${date(s.ends_at)}</p><p>${esc(s.place)}</p><p><strong>${esc(status(s))}</strong></p>${canCheck&&active&&s.attendance!=='present'?`<button class="btn checkin" data-checkin="${key}" ${open?'':'disabled'}>${open?'출석하기':'출석 가능 시간이 아닙니다'}</button><p class="member-label">출석 가능 ${date(s.opens_at)} ~ ${date(s.closes_at)}</p>${now<=new Date(s.closes_at)?`<details><summary>결석 예정 입력</summary><form data-absence="${key}">${field('reason','결석 사유','text','maxlength="500"')}<button class="btn secondary">결석 예정 저장</button></form></details>`:''}`:''}${active?`<details><summary>내 캘린더에 추가</summary><div class="toolbar"><a class="btn secondary" href="${esc(googleCalendar({...s,workspace_name:s.workspace_name}))}" target="_blank" rel="noopener noreferrer">Google Calendar</a><button class="btn secondary" data-ics="${key}">Apple Calendar · ICS</button></div><p class="member-label">개별 일정을 저장합니다. 이후 일정 변경은 자동 반영되지 않습니다.</p></details>`:''}</section>`;}).join('');}
function calendar(){const [y,m]=month.split('-').map(Number),start=new Date(Date.UTC(y,m-1,1)).getUTCDay(),count=new Date(Date.UTC(y,m,0)).getUTCDate();let cells='<div class="weekday">일</div>'+['월','화','수','목','금','토'].map(d=>`<div class="weekday">${d}</div>`).join('')+'<span></span>'.repeat(start);for(let n=1;n<=count;n++){const d=month+'-'+String(n).padStart(2,'0'),events=shownRows().filter(s=>kday(s.starts_at)===d);cells+=`<button data-day="${d}" class="${d===selectedDay?'selected':''}" aria-label="${d} 일정 ${events.length}개">${n}${events.length?`<small>${events.length}개</small>`:''}</button>`;}return `<section class="card"><h1>찬양대 일정</h1><div class="calendar-controls"><button class="btn secondary" data-month-step="-1" aria-label="이전 달">‹</button><input id="calendar-month" aria-label="조회 월" type="month" min="2000-01" max="2100-12" value="${month}"><button class="btn secondary" data-month-step="1" aria-label="다음 달">›</button></div><div class="cal-grid">${cells}</div></section><h2>${esc(selectedDay)} 일정</h2>${cards(shownRows().filter(s=>kday(s.starts_at)===selectedDay))||empty('이날은 등록된 일정이 없습니다.')}`;}
function history(){const r=report(shownRows(),year,reportMonth,query);return `<section class="card"><h1>내 출결</h1><div class="form-grid"><label class="field">연도<input id="report-year" type="number" min="2000" max="2100" value="${year}"></label><label class="field">기간<select id="report-month"><option value="">연간 전체</option>${Array.from({length:12},(_,i)=>`<option value="${String(i+1).padStart(2,'0')}" ${reportMonth===String(i+1).padStart(2,'0')?'selected':''}>${i+1}월</option>`).join('')}</select></label></div><form id="search"><label class="field">일정·찬양대·장소·사유 검색<input name="search" value="${esc(query)}" placeholder="검색어를 입력하세요"></label><button class="btn secondary">검색</button></form><div class="report-stats">${[['present','출석'],['absent','결석'],['excused','공결'],['unrecorded','미기록']].map(([k,label])=>`<div><strong>${r.counts[k]}</strong>${label}</div>`).join('')}</div><p class="member-label">취소 일정은 집계에서 제외합니다. 마감 후 기록이 없는 일정은 ‘미기록’으로 구분합니다.</p></section>${cards(r.rows.slice().reverse(),false)||empty('조회된 기록이 없습니다.')}`;}
function profile(){const photo=typeof data.photo==='string'&&data.photo.startsWith('data:image/jpeg;base64,')?`<img class="profile-photo" src="${esc(data.photo)}" alt="내 프로필 사진">`:'<div class="profile-photo" aria-hidden="true"></div>';return `<section class="card"><h1>내 정보</h1><div class="photo-row">${photo}<div><h2>${esc(data.name)}</h2><p>${esc(data.workspace)} · ${esc(data.login_id||'')}</p></div></div><form id="photo"><label class="field">프로필 사진<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required></label><button class="btn secondary">사진 저장</button></form>${data.photo?'<button class="btn secondary" id="delete-photo">사진 삭제</button>':''}<p class="member-label">사진은 작은 크기로 변환해 내 프로필에 저장합니다.</p></section><section class="card"><h2>내 찬양대</h2>${(data.memberships||[]).map(m=>`<p><strong>${esc(data.workspace+' · '+m.name)}</strong><br>${esc(m.part)} · ${m.roles.map(r=>({member:'단원',leader:'파트장',secretary:'서기',admin:'관리자'}[r]||r)).map(esc).join(', ')}</p>${m.roles.includes('admin')?`<button class="btn secondary" data-invite-choir="${esc(m.choir_id)}">이 합창단 단원 초대</button>`:''}`).join('')||'<p>소속 정보를 불러오려면 추가 설정(005)을 적용해 주세요.</p>'}<div class="toolbar"><button class="btn" id="change-pin">PIN 변경</button><button class="btn secondary" id="logout">로그아웃</button></div></section>`;}
function staffView(){const members=staffMemberships();if(!members.length)return empty('출결 관리 권한이 없습니다.');return `<section class="card"><h1>출결 관리</h1><p>파트장은 자기 파트, 서기·관리자는 찬양대 전체를 조회·정정합니다.</p><label class="field">찬양대<select id="staff-choir">${members.map(m=>`<option value="${m.choir_id}" ${staffChoir===m.choir_id?'selected':''}>${esc(data.workspace+' · '+m.name)}</option>`).join('')}</select></label>${staff?`<form id="staff-correct"><label class="field">일정<select name="session_id" id="staff-session">${staff.sessions.map(s=>`<option value="${s.id}">${esc(s.title)} · ${date(s.starts_at)}</option>`).join('')}</select></label><div id="staff-list"></div><label class="field">단원<select name="member_id">${staff.members.map(m=>`<option value="${m.id}">${esc(m.name)} · ${esc(m.part)}</option>`).join('')}</select></label><label class="field">출결<select name="status"><option value="present">출석</option><option value="absent">결석</option><option value="excused">공결</option></select></label>${field('reason','정정 사유','text','maxlength="500"')}<button class="btn" ${!staff.sessions.length||!staff.members.length?'disabled':''}>정정 저장</button></form>`:'<p>출결 정보를 불러오고 있습니다.</p>'}</section>`;}
function staffList(){if(!staff)return;const sid=root.querySelector('#staff-session')?.value,el=root.querySelector('#staff-list');if(el)el.innerHTML=staff.members.map(m=>`<p>${esc(m.name)} · ${esc(m.part)}: ${{present:'출석',absent:'결석',excused:'공결'}[staff.attendance.find(a=>a.session_id===sid&&a.member_id===m.id)?.status]||'미기록'}</p>`).join('');}
function render(){if(!data)return;let body='';if(view==='home'){const rows=shownRows().filter(s=>kday(s.starts_at)===today());body=`<section class="welcome"><p>함께하는 찬양</p><h1>${sessions.size>1?'내 합창단 모아보기':esc(data.workspace)}</h1><p>${esc(data.name)}님, 반갑습니다.</p></section><h2>오늘의 일정</h2>${cards(rows)||empty('오늘은 등록된 일정이 없습니다. 일정 메뉴에서 다른 날짜를 확인하세요.')}`;}if(view==='calendar')body=calendar();if(view==='history')body=history();if(view==='profile')body=profile();if(view==='staff')body=staffView();root.innerHTML=(['home','calendar','history'].includes(view)?overviewControls():'')+body+nav();if(view==='staff')staffList();}
async function go(next){if(next==='home'&&year!==currentYear())await refreshAll(currentYear());if(next==='calendar'&&year!==Number(month.slice(0,4)))await refreshAll(Number(month.slice(0,4)));if(next==='staff'){staffChoir=staffMemberships().find(m=>m.choir_id===staffChoir)?.choir_id||staffMemberships()[0]?.choir_id;if(staffChoir)staff=await action('staff',{choir_id:staffChoir});}view=next;render();}
function workspaceScreen(){root.innerHTML=`<section class="card"><h1>내 합창단 · 계정</h1><p>각각 로그인하면 홈과 일정에서 함께 볼 수 있습니다. 새로고침하거나 앱을 다시 열면 로그인이 필요합니다.</p>${remembered.map(w=>`<div class="toolbar"><strong>${esc(w.name)}</strong><button class="btn secondary" data-workspace="${w.id}">${sessions.has(w.id)?'이 계정 선택':'로그인'}</button>${connectionErrors.has(w.id)?`<button class="btn secondary" data-relogin="${w.id}">다시 로그인</button>`:''}</div>`).join('')||'<p>아직 저장한 Workspace가 없습니다.</p>'}<p><a class="btn secondary" href="./member-join.html">회원가입 · 가입 링크 입력</a></p><form id="add-workspace">${field('link','추가할 합창단의 단원 접속 링크','url','placeholder="https://…/member.html?workspace=…"')}<button class="btn">합창단 추가</button></form>${data?'<button class="btn secondary" data-view="home">돌아가기</button>':''}</section>`;}
async function switchTo(id){if(!valid(id))throw Error('단원 접속 링크를 확인해 주세요.');if(sessions.has(id)){const t=sessions.get(id);const next=await rpc('choiron_member_action',{p_token:t,p_action:'data',p_data:{year:currentYear()}});workspace=id;token=t;data=next;data.year=currentYear();snapshots.set(id,data);connectionErrors.delete(id);year=currentYear();view='home';staff=null;applyTheme(data.theme,data.logo);setAppIcon(data.logo).catch(()=>{});remember();await refreshAll();render();}else{workspace=id;token='';data=null;staff=null;login();}}
async function run(fn){if(busy)return;busy=true;const controls=[...document.querySelectorAll('button,select,input')].map(b=>[b,b.disabled]);controls.forEach(([b])=>b.disabled=true);message.textContent='처리 중입니다…';try{await fn();}catch(e){message.textContent=e.name==='TimeoutError'?'응답이 늦어지고 있습니다. 잠시 후 다시 확인해 주세요.':e.message;}finally{busy=false;controls.forEach(([b,disabled])=>{if(b.isConnected)b.disabled=disabled;});}}
const find=key=>allRows().find(s=>s.workspace_id+'/'+s.choir_id+'/'+s.id===key);
root.addEventListener('submit',e=>{e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f)),id=f.getAttribute('id');run(async()=>{
 if(id==='login'){const result=await rpc('choiron_member_login',{p_workspace:workspace,p_login_id:v.loginId,p_pin:v.pin});token=result.token;f.elements.pin.value='';delete v.pin;if(result.must_change)pin(true);else{await load(currentYear());view='home';render();}message.textContent='';}
 else if(id==='pin'){if(v.pin!==v.confirm)throw Error('두 PIN이 일치하지 않습니다.');await action('pin',{pin:v.pin});f.reset();await load();view='home';render();message.textContent='PIN을 변경했습니다.';}
 else if(id==='photo'){const photo=await photoData(v.photo);await action('photo',{photo});await load();render();message.textContent='사진을 저장했습니다.';}
 else if(id==='search'){query=v.search;render();message.textContent='';}
 else if(id==='add-workspace'){const url=new URL(v.link);const target=url.searchParams.get('workspace');if(!['http:','https:'].includes(url.protocol)||url.origin!==location.origin)throw Error('현재 ChoirON 사이트에서 받은 단원 링크를 입력해 주세요.');await switchTo(target);message.textContent='';}
 else if(id==='staff-correct'){await action('staff_correct',{choir_id:staffChoir,...v});staff=await action('staff',{choir_id:staffChoir});await load();render();message.textContent='정정 내용을 저장했습니다.';}
 else if(f.dataset.absence){const s=find(f.dataset.absence);if(!s)throw Error('일정을 새로고침해 주세요.');await scopedAction(s.workspace_id,'absence',{session_id:s.id,choir_id:s.choir_id,reason:v.reason});await refreshOne(s.workspace_id);render();message.textContent='결석 예정을 저장했습니다.';}
});});
root.addEventListener('click',e=>{if(busy)return;const b=e.target.closest('button');if(!b)return;
 if(b.dataset.view)run(async()=>{await go(b.dataset.view);message.textContent='';});
 if(b.dataset.day){selectedDay=b.dataset.day;render();}
 if(b.dataset.monthStep)run(async()=>{const [y,m]=month.split('-').map(Number),d=new Date(Date.UTC(y,m-1+Number(b.dataset.monthStep),1));await setMonth(d.toISOString().slice(0,7));});
 if(b.dataset.workspace)run(async()=>{try{await switchTo(b.dataset.workspace);message.textContent='';}catch(e){connectionErrors.set(b.dataset.workspace,e.message);message.textContent=e.message+' 다시 로그인 버튼을 이용해 주세요.';}});
 if(b.dataset.relogin)run(async()=>{workspace=b.dataset.relogin;sessions.delete(workspace);snapshots.delete(workspace);connectionErrors.delete(workspace);token='';data=null;login();message.textContent='';});
 if(b.dataset.retry||b.id==='refresh-all')run(async()=>{await refreshAll();render();message.textContent='불러온 일정을 갱신했습니다.';});
 if(b.dataset.inviteChoir){const c=data.memberships.find(m=>m.choir_id===b.dataset.inviteChoir&&m.roles.includes('admin'));if(c){root.innerHTML='<section class="card" id="enrollment"></section><button class="btn secondary" data-view="profile">내 정보로 돌아가기</button>';invitePanel({host:root.querySelector('#enrollment'),rpc,workspace,choir:c.choir_id,label:data.workspace+' · '+c.name,session:token});}}
 if(b.id==='change-pin')pin(false);
 if(b.id==='skip-pin')run(async()=>{await action('skip_pin');await load(currentYear());view='home';render();message.textContent='현재 PIN을 그대로 사용합니다. 내 정보에서 언제든 변경할 수 있습니다.';});
 if(b.id==='delete-photo')run(async()=>{await action('photo',{photo:null});await load();render();message.textContent='사진을 삭제했습니다.';});
 if(b.id==='logout')run(async()=>{try{await action('logout');}finally{sessions.delete(workspace);snapshots.delete(workspace);connectionErrors.delete(workspace);token='';data=null;workspaceScreen();message.textContent='이 화면에서 로그아웃했습니다.';}});
 if(b.dataset.checkin)run(async()=>{const s=find(b.dataset.checkin);if(!s)throw Error('일정을 새로고침해 주세요.');const pos=await position();await scopedAction(s.workspace_id,'checkin',{session_id:s.id,choir_id:s.choir_id,...pos});await refreshOne(s.workspace_id);render();message.textContent='출석했습니다.';});
 if(b.dataset.ics){const s=find(b.dataset.ics),blob=new Blob([ics(s,s.workspace_id)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ChoirON-'+s.id+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);message.textContent='다운로드한 일정을 캘린더 앱에서 열어 주세요.';}
});
async function setMonth(value){if(!/^\d{4}-\d{2}$/.test(value)||Number(value.slice(0,4))<2000||Number(value.slice(0,4))>2100)throw Error('2000~2100년 사이로 선택해 주세요.');const y=Number(value.slice(0,4));if(year!==y)await refreshAll(y);month=value;selectedDay=value+'-01';render();message.textContent='';}
root.addEventListener('change',e=>{if(busy)return;const el=e.target;if(el.id==='choir-filter'){choirFilter=el.value;render();}if(el.id==='calendar-month')run(()=>setMonth(el.value));if(el.id==='report-year')run(async()=>{const y=Number(el.value);if(!Number.isInteger(y)||y<2000||y>2100)throw Error('2000~2100년 사이로 선택해 주세요.');await refreshAll(y);render();message.textContent='';});if(el.id==='report-month'){reportMonth=el.value;render();}if(el.id==='staff-choir')run(async()=>{const next=await action('staff',{choir_id:el.value});staffChoir=el.value;staff=next;render();message.textContent='';});if(el.id==='staff-session')staffList();});
document.querySelector('#workspaces').addEventListener('click',()=>{if(!busy){workspaceScreen();message.textContent='';}});
if(valid(workspace))login();else workspaceScreen();

