import {appearance} from './appearance.js';
import {applyTheme} from './themes.js';
import {manage} from './manage.js?v=9';
import {supabaseConfig as config} from './supabase-config.js';
const screen=document.querySelector('#screen'),message=document.querySelector('#message');
let accessToken='',busy=false,requestId='',myWorkspaces=[],isOperator=false,serviceWorkspaces=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path,body,token=accessToken) {
 const headers={'apikey':config.publishableKey,'Content-Type':'application/json'};
 if(token)headers.Authorization='Bearer '+token;
 const response=await fetch(config.url+path,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});
 const raw=await response.text();let result;try{result=raw?JSON.parse(raw):null;}catch{throw Error('서버 응답을 확인할 수 없습니다.');}
 if(!response.ok){
  const code=result?.error_code||result?.code||result?.error;
  const detail=result?.message||result?.msg||result?.error_description||'';
  if(code==='invalid_credentials'||detail==='Invalid login credentials')throw Error('이메일 또는 비밀번호가 일치하지 않습니다. 브라우저 자동 입력 대신 관리자 비밀번호를 직접 입력해 주세요. 단원 PIN과는 다릅니다.');
  if(code==='email_not_confirmed')throw Error('이 계정은 이전 이메일 인증 방식에서 대기 중입니다. 운영자에게 계정 상태 확인을 요청해 주세요.');
  if(response.status===429)throw Error('로그인 시도가 많아 잠시 제한되었습니다. 잠시 후 다시 시도해 주세요.');
  if(code==='PGRST202')throw Error('서버 기능 설정이 필요합니다. 최종 SQL 008이 적용됐는지 확인해 주세요.');
  if(response.status===401)throw Error('이메일·비밀번호를 확인해 주세요. 로그인 시간이 만료됐다면 새로고침 후 다시 로그인해 주세요.');
  throw Error(detail||`요청을 처리하지 못했습니다. (HTTP ${response.status}, ${code||'unknown'})`);
 }
 return result;
}
function login(){accessToken='';screen.innerHTML=`<section class="card"><form id="login"><label class="field">관리자 이메일<input name="email" type="email" autocomplete="username" placeholder="이메일 주소" required></label><label class="field">관리자 비밀번호<input name="password" type="password" autocomplete="current-password" required></label><p class="muted">처음 설정하거나 초대 가입할 때 정한 이메일·비밀번호로 로그인하세요.</p><button class="btn" type="submit">로그인</button></form></section>`;}
async function overview(){
 screen.onclick=null;screen.onsubmit=null;screen.onchange=null;applyTheme();
 const portal=await request('/rest/v1/rpc/choiron_admin_portal',{});myWorkspaces=portal.mine;isOperator=portal.operator;const service=portal.service;serviceWorkspaces=service?.workspaces||[];
 screen.innerHTML=`<section class="card"><div class="row"><h2>${isOperator?'운영자 연결 완료':'내 Workspace'}</h2><button class="btn secondary" id="logout">로그아웃</button></div>${isOperator?`<p>Workspace ${service.workspaces.length}개 · 초대 ${service.invitations.length}개</p><div class="toolbar"><button class="btn" id="invite">Workspace 관리자 초대</button><button class="btn secondary" id="setup">내 Workspace 만들기</button></div>${service.workspaces.map(w=>`<section class="card"><h3>${esc(w.name)}</h3>${(w.admins||[]).map(a=>`<p>${esc(a.name)} · ${esc(a.email)} · ${a.revoked_at?'권한 취소됨':`관리 중 <button class="btn secondary" data-remove-admin="${esc(a.auth_id)}" data-wid="${esc(w.id)}">관리 권한 취소</button>`}</p>`).join('')}${w.status==='active'&&w.admins&&!w.admins.some(a=>!a.revoked_at)?`<button class="btn" data-transfer="${esc(w.id)}">새 관리자에게 인계 링크 보내기</button>`:''}</section>`).join('')}<button class="btn secondary" id="refresh-portal">목록 새로고침</button><details><summary>초대 내역</summary>${service.invitations.map(i=>`<p>${esc(i.workspace_name)} · ${esc(i.email)}<br>${i.accepted_at?'가입 완료':i.revoked_at?'취소됨':new Date(i.expires_at)<new Date()?'만료됨':'가입 대기'} ${!i.accepted_at&&!i.revoked_at&&new Date(i.expires_at)>new Date()?`<button class="btn secondary" data-revoke="${i.id}">초대 취소</button>`:''}</p>`).join('')||'<p>아직 초대가 없습니다.</p>'}</details>`:''}</section>${myWorkspaces.map(w=>`<section class="card"><h2>${esc(w.name)}</h2><p>관리자: ${esc(w.admin_name)} · 아이디: ${esc(w.login_id)}</p><p>찬양대: ${w.choirs.map(c=>esc(w.name+' · '+c.name)).join(', ')}</p><div class="toolbar"><button class="btn" data-manage="${esc(w.id)}">단원·일정 관리</button><button class="btn secondary" data-appearance="${esc(w.id)}">디자인 설정</button><button class="btn secondary" data-handoff="${esc(w.id)}">후임 관리자에게 인계</button></div></section>`).join('')||(!isOperator?'<section class="card">연결된 Workspace가 없습니다. 운영자가 보내 준 초대 링크로 가입을 완료해 주세요.</section>':'')}`;
 message.textContent='계정과 권한을 확인했습니다.';
}
function invite(){screen.innerHTML=`<section class="card"><h2>Workspace 관리자 초대</h2><p>초대한 담당자에게 새 Workspace를 제공합니다.</p><form id="invite-form"><label class="field">교회·단체 이름<input name="name" maxlength="80" required></label><label class="field">담당자 이메일<input name="email" type="email" maxlength="254" required></label><p>초대는 7일 동안 유효합니다. 이메일은 자동 발송하지 않으며, 생성한 링크를 직접 전달합니다.</p><button class="btn">초대 링크 만들기</button></form><button class="btn secondary" id="back">돌아가기</button><div id="invite-result"></div></section>`;}
function showInvite(invitation){const link=new URL('./join.html',location.href);link.hash='invite='+invitation.token;screen.querySelector('#invite-result').innerHTML=`<h3>관리자 초대 링크</h3><textarea id="invite-link" readonly aria-label="초대 링크">${esc(link.href)}</textarea><button class="btn secondary" id="copy-invite">링크 복사</button><p>지정한 담당자에게 직접 전달하세요. 링크는 7일간 유효하며 한 번만 사용할 수 있습니다. 이메일은 자동 발송하지 않습니다.</p>`;message.textContent='링크를 만들었습니다.';}
function handoff(w,mode){screen.innerHTML=`<section class="card"><h2>${esc(w.name)} 관리자 인계</h2><p>단원·찬양대·일정·출결은 그대로 유지합니다. ${mode==='handoff'?'후임자가 인수를 완료하면 현재 계정은 이 Workspace에 접근할 수 없습니다.':'링크를 받은 후임자가 같은 Workspace의 관리자가 됩니다.'}</p><form id="invite-form"><input type="hidden" name="mode" value="${mode}"><input type="hidden" name="workspace" value="${esc(w.id)}"><label class="field">후임자 이메일<input name="email" type="email" required maxlength="254"></label><button class="btn">인계 링크 만들기</button></form>${mode==='handoff'?`<button class="btn secondary" data-cancel-handoff="${esc(w.id)}">아직 사용하지 않은 인계 링크 취소</button>`:''}<button class="btn secondary" id="back">돌아가기</button><div id="invite-result"></div></section>`;message.textContent='';}
function setup(){
 requestId=crypto.randomUUID();message.textContent='';
 screen.innerHTML=`<section class="card"><h2>우리 Workspace 시작하기</h2><p>Google 설정이나 별도 파일 연결 없이 한 번에 만듭니다.</p><form id="create-workspace"><label class="field">교회·단체 이름<input name="workspace" placeholder="예: 신광교회" maxlength="80" required></label><label class="field">관리자 이름<input name="admin" placeholder="본인 이름" maxlength="80" required></label><label class="field">관리자 아이디<input name="loginId" placeholder="한글 이름도 가능합니다" maxlength="64" required></label><p class="muted">한글·영문·숫자·밑줄·붙임표를 띄어쓰기 없이 입력하세요. 지금은 기존 이메일·비밀번호로 로그인하며, PIN은 입력하지 않습니다.</p><label class="field">첫 찬양대 이름<input name="choir" placeholder="예: 예루살렘 찬양대" maxlength="80" required></label><div class="toolbar"><button class="btn" type="submit">Workspace 만들기</button><button class="btn secondary" type="button" id="back">돌아가기</button></div></form></section>`;
}
async function task(fn){if(busy)return;busy=true;screen.querySelectorAll('button').forEach(b=>b.disabled=true);message.textContent='처리 중입니다…';try{await fn();}catch(e){message.textContent=e.name==='TimeoutError'?'연결이 지연되고 있습니다. 같은 화면에서 다시 시도해 주세요.':e.message;}finally{busy=false;if(message.textContent==='처리 중입니다…')message.textContent='';screen.querySelectorAll('button').forEach(b=>b.disabled=b.dataset.unavailable==='true');}}
 screen.addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.target);
 if(e.target.id==='invite-form')task(async()=>{const mode=form.get('mode'),wid=form.get('workspace');const invitation=await request('/rest/v1/rpc/'+(mode==='handoff'?'choiron_admin_handoff':mode==='transfer'?'choiron_operator_transfer_invite':'choiron_operator_invite'),mode?{p_workspace:wid,p_email:form.get('email')}:{p_name:form.get('name'),p_email:form.get('email')});showInvite(invitation);});
 if(e.target.id==='login')task(async()=>{const session=await request('/auth/v1/token?grant_type=password',{email:form.get('email'),password:form.get('password')},'');accessToken=session.access_token;form.delete('password');e.target.elements.password.value='';await overview();});
 if(e.target.id==='create-workspace')task(async()=>{await request('/rest/v1/rpc/choiron_setup_workspace',{p_request_id:requestId,p_name:form.get('workspace'),p_admin_name:form.get('admin'),p_login_id:form.get('loginId'),p_choir_name:form.get('choir')});try{await overview();message.textContent='Workspace와 관리자, 첫 찬양대를 만들었습니다.';}catch{message.textContent='저장됐습니다. 목록을 불러오지 못했으니 돌아가기를 눌러 확인해 주세요.';}});
});
screen.addEventListener('click',e=>{if(busy)return;if(e.target.id==='invite'&&isOperator){invite();return;}if(e.target.id==='copy-invite'){task(async()=>{await navigator.clipboard.writeText(screen.querySelector('#invite-link').value);message.textContent='복사했습니다.';});return;}if(e.target.id==='refresh-portal'){task(overview);return;}if(e.target.dataset.handoff){const w=myWorkspaces.find(w=>w.id===e.target.dataset.handoff);if(w)handoff(w,'handoff');return;}if(e.target.dataset.transfer&&isOperator){const w=serviceWorkspaces.find(w=>w.id===e.target.dataset.transfer);if(w)handoff(w,'transfer');return;}if(e.target.dataset.cancelHandoff){task(async()=>{await request('/rest/v1/rpc/choiron_admin_cancel_handoff',{p_workspace:e.target.dataset.cancelHandoff});screen.querySelector('#invite-result').innerHTML='';message.textContent='미사용 인계 링크를 취소했습니다.';});return;}if(e.target.dataset.removeAdmin&&isOperator){if(!confirm('이 관리자의 해당 Workspace 접근을 즉시 차단하시겠습니까? 단원과 출결 데이터는 유지됩니다.'))return;task(async()=>{await request('/rest/v1/rpc/choiron_operator_remove_admin',{p_workspace:e.target.dataset.wid,p_auth_id:e.target.dataset.removeAdmin});await overview();message.textContent='관리 권한을 취소했습니다. 새 관리자에게 인계 링크를 만들 수 있습니다.';});return;}if(e.target.dataset.revoke){task(async()=>{await request('/rest/v1/rpc/choiron_operator_revoke',{p_id:e.target.dataset.revoke});await overview();message.textContent='초대를 취소했습니다.';});return;}if(e.target.dataset.appearance){const workspace=myWorkspaces.find(w=>w.id===e.target.dataset.appearance);if(workspace)appearance({root:screen,workspace,rpc:(name,args)=>request('/rest/v1/rpc/'+name,args),back:()=>task(overview)});return;}if(e.target.dataset.manage){const workspace=myWorkspaces.find(w=>w.id===e.target.dataset.manage);if(workspace){applyTheme(workspace.theme,workspace.logo);task(()=>manage({root:screen,workspace,rpc:(name,args)=>request('/rest/v1/rpc/'+name,args),back:()=>task(overview)}));}return;}if(e.target.id==='setup')setup();if(e.target.id==='back')task(overview);if(e.target.id==='logout')task(async()=>{const token=accessToken;login();try{await request('/auth/v1/logout',{},token);message.textContent='로그아웃했습니다.';}catch{message.textContent='이 화면에서는 로그아웃했습니다. 서버 로그아웃은 확인하지 못했습니다.';}});});
login();

