const root=document.querySelector('#guide'),notice=document.querySelector('#notice');
let step=0;try{step=Math.max(0,Math.min(4,Number(localStorage.getItem('choiron-free-guide-step'))||0));}catch{}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=[
 ['우리 Workspace를 시작해 볼까요?',`<p>별도 서버 구매나 Google Cloud 결제 설정 없이 시작합니다. 처음 한 번, Workspace 관리자의 Google 계정에서 연결 프로그램을 준비합니다.</p><ol><li>Google에 프로그램 복사</li><li>초기 설정 키 준비</li><li>웹 앱으로 배포</li><li>찬양대·단원·출석 장소 설정</li></ol><div class="hint">준비물: 관리자 Google 계정과 컴퓨터. 휴대폰보다는 컴퓨터에서 진행해 주세요.</div><p>이미 연결을 완료하셨다면 <a href="./">단원 앱으로 돌아가기</a>를 선택하세요.</p>`],
 ['Google에 연결 프로그램 넣기',`<ol><li><a href="https://script.google.com/home/start" target="_blank" rel="noopener">Google Apps Script 열기 ↗</a>를 누르고 <b>Workspace 관리자 계정</b>으로 새 프로젝트를 만듭니다. 이름은 ‘우리 찬양대 ChoirON’처럼 정합니다.</li><li>아래 <b>프로그램 복사</b>를 누릅니다. Google 편집기의 <b>Code.gs</b> 내용을 모두 지우고 붙여넣은 뒤 저장합니다.</li><li>왼쪽 <b>프로젝트 설정(톱니바퀴)</b>에서 ‘편집기에 appsscript.json 매니페스트 파일 표시’를 켭니다.</li><li>편집기로 돌아와 <b>appsscript.json</b>을 선택하고 <b>설정 파일 복사</b>의 내용으로 바꾼 뒤 저장합니다.</li></ol><div class="toolbar"><button class="btn" data-copy="ChoirON.gs.txt">프로그램 복사</button><button class="btn secondary" data-copy="appsscript.json.txt">설정 파일 복사</button></div><p><a href="./install/ChoirON.gs.txt" download>프로그램 파일 다운로드</a> · <a href="./install/appsscript.json.txt" download>설정 파일 다운로드</a></p><p class="muted">여러 파일을 만들 필요 없이 프로그램 하나와 설정 파일 하나만 넣으면 됩니다.</p>`],
 ['초기 설정 키 준비하기',`<ol><li>Google 편집기 위쪽 함수 선택 목록에서 <b>prepareInstall</b>을 선택합니다.</li><li><b>실행</b>을 누르고 본인이 복사한 프로그램의 Google 권한 요청을 확인합니다. 이 프로그램은 Sheets·Drive와 자동 백업에 필요한 권한을 사용합니다.</li><li>실행 로그에 나오는 <b>일회용 초기 설정 키</b>를 복사해 잠시 보관합니다. 다음 설정 화면에서 사용합니다.</li></ol><div class="hint">이 키를 단원에게 보내거나 GitHub에 올리지 마세요. 초기화가 끝나면 재사용할 수 없습니다.</div><details><summary>권한 안내나 차단 화면이 나온다면</summary><p>본인이 만든 스크립트인지와 실행 계정을 확인하세요. 조직 정책으로 실행이 차단되면 해당 Google 계정의 조직 관리자에게 문의해야 합니다. 정책을 우회하지 마세요.</p></details>`],
 ['웹 앱으로 배포하기',`<ol><li>Google 편집기 오른쪽 위 <b>배포 → 새 배포</b>를 누릅니다.</li><li>유형 선택에서 <b>웹 앱</b>을 선택합니다.</li><li>실행 사용자는 <b>나</b>, 액세스 권한은 <b>모든 사용자</b>로 설정하고 배포합니다.</li><li>표시되는 <b>웹 앱 URL</b>을 복사합니다. 주소 끝이 <b>/exec</b>인지 확인해 주세요.</li></ol><p>주소가 공개되어도 앱 안에서는 단원 ID·PIN과 서버 권한 검사로 데이터를 보호합니다. 원본 Sheet를 단원에게 공유할 필요는 없습니다.</p><details><summary>‘모든 사용자’ 항목이 보이지 않나요?</summary><p>조직의 Google 정책에서 공개 배포를 제한할 수 있습니다. 조직 관리자에게 배포 가능 여부를 확인하세요. ‘Google 계정이 있는 사용자’로 바꾸면 현재 연결 방식이 동작하지 않을 수 있습니다.</p></details>`],
 ['이제 찬양대 정보를 입력하세요',`<p>복사한 <b>웹 앱 URL</b>과 <b>일회용 초기 설정 키</b>를 준비하셨나요? 다음 화면에서 아래 순서대로 입력합니다.</p><ol><li>Workspace 이름·코드·연결 주소·초기 설정 키</li><li>관리자 이름·단원 ID·PIN</li><li>찬양대 이름</li><li>첫 단원 등록</li><li>출석 장소와 연습 일정</li></ol><p>Sheet ID는 비워두면 자동으로 만듭니다. 각 찬양대의 출결은 별도 Sheet에 저장됩니다.</p><a class="btn" href="./?setup=1">Workspace 설정 시작</a><p>중간에 닫았다면 단원 앱에 관리자 ID로 로그인하고 <b>설정</b>에서 남은 항목을 등록할 수 있습니다. 이미 초기화한 프로그램에 초기 설정을 반복하지 마세요.</p>`]
];
function render(){const [title,body]=pages[step];root.innerHTML=`<div class="setup-progress">${pages.map((_,i)=>`<span class="${i<=step?'done':''}"></span>`).join('')}</div><p class="eyebrow">시작 안내 ${step+1} / ${pages.length}</p><h1>${title}</h1><section class="card">${body}</section><div class="toolbar">${step?'<button class="btn secondary" data-step="-1">이전</button>':''}${step<4?'<button class="btn" data-step="1">'+(step===0?'설정 시작하기':'완료했어요 · 다음')+'</button>':''}<a class="btn secondary" href="./">앱 둘러보기</a></div>`;notice.textContent='';}
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.step){step+=Number(b.dataset.step);try{localStorage.setItem('choiron-free-guide-step',step);}catch{}render();scrollTo(0,0);}if(b.dataset.copy){try{const r=await fetch('./install/'+b.dataset.copy);if(!r.ok)throw Error('파일을 열지 못했습니다.');const text=await r.text();await navigator.clipboard.writeText(text);notice.textContent='복사했습니다. Google 편집기에 붙여넣어 주세요.';}catch{notice.textContent='자동 복사가 제한되었습니다. 아래 파일을 다운로드해 열고 전체 내용을 복사해 주세요.';}}});
render();
